#!/usr/bin/env python3
"""Generate the cake (Cake) tiles (16x16, original procedural pixel art).

t1112 roster medium-tier batch: two new atlas tiles 207/208 (cake_top frosting
face / cake_side sponge + frosting band), generated by this script (§9a original
pixel art, zero MC assets). The block's per-bite visual is geometry-driven (the
-X side shrinks 2px per bite via the ShapeCake box + PartialBlockGeometry case),
so no per-bite tiles are needed.
"""
import os
import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "..", "textures")
TS = 16

# 霜面配色（§9a 原创自绘——蛋糕顶面奶油霜 + 红色果饰点，零 MC 文本专名资产）。
FROST = (236.0, 234.0, 224.0)
FROST_L = (248.0, 246.0, 246.0)
FROST_D = (212.0, 208.0, 194.0)
DOT = (196.0, 62.0, 56.0)
DOT_L = (224.0, 96.0, 88.0)
SPONGE = (214.0, 172.0, 108.0)
SPONGE_D = (182.0, 138.0, 78.0)
BAND = (236.0, 234.0, 224.0)
BAND_D = (212.0, 208.0, 194.0)


def draw_cake_top():
    """顶面：乳白霜面 + 暗边框 + 对角高光斜线 + 红色果饰点阵（3x3 均布）。"""
    c = np.zeros((TS, TS, 4), np.float64)
    c[..., 0:3] = FROST
    c[..., 3] = 255.0
    c[0, :, 0:3] = FROST_D
    c[TS - 1, :, 0:3] = FROST_D
    c[:, 0, 0:3] = FROST_D
    c[:, TS - 1, 0:3] = FROST_D
    # 对角高光斜线（左上受光）
    for i in range(1, TS - 1):
        c[i, i + 1, 0:3] = FROST_L
    # 红色果饰点阵（3x3 均布，点径 1px + 上侧高光）
    for gy in (4, 8, 12):
        for gx in (4, 8, 12):
            c[gy, gx, 0:3] = DOT
            c[gy - 1, gx, 0:3] = DOT_L
    return c


def draw_cake_side():
    """侧面：上部霜带（4px）+ 下部海绵糕体（层理暗纹 + 底部暗边 + 霜滴落两处）。"""
    c = np.zeros((TS, TS, 4), np.float64)
    c[..., 0:3] = SPONGE
    c[..., 3] = 255.0
    # 上部霜带 rows 0..3（霜底 + 下沿暗线）
    c[0:4, :, 0:3] = BAND
    c[4, :, 0:3] = BAND_D
    # 下部海绵糕体 rows 5..15（暖黄海绵 + 层理暗纹 + 底边暗线）
    for y in (7, 11, 14):
        c[y, :, 0:3] = SPONGE_D
    c[TS - 1, :, 0:3] = SPONGE_D
    # 霜带下沿滴落（两处 2px 垂霜滴）
    c[4:6, 4, 0:3] = BAND
    c[4:6, 12, 0:3] = BAND
    return c


def save(arr, name):
    img = Image.fromarray(np.clip(arr, 0, 255).astype(np.uint8), "RGBA")
    out = os.path.join(SRC, name + ".png")
    img.save(out)
    print("wrote", os.path.relpath(out, HERE), img.size)


if __name__ == "__main__":
    save(draw_cake_top(), "default_cake_top")
    save(draw_cake_side(), "default_cake_side")
